services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-mlflow-data:/var/lib/postgresql/data
    networks:
      - mlflow-network
    logging:
      options:
        max-size: 10m
        max-file: "3"

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DEFAULT_ARTIFACT_ROOT: ${DEFAULT_ARTIFACT_ROOT}
      BACKEND_STORE_URI: ${BACKEND_STORE_URI}
    volumes:
      - ./secrets:/app/secrets
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - mlflow-network
    logging:
      options:
        max-size: 10m
        max-file: "3"

volumes:
  postgres-mlflow-data:

networks:
  mlflow-network:
